[project]
name = "chuot-chat"
version = "1.0.0"
description = "Chuột Chat Flask app"
requires-python = ">=3.11"
dependencies = [
    "flask==2.3.2",
    "requests==2.31.0",
]
[project.optional-dependencies]
postgres = ["psycopg2-binary==2.9.7"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "chuot-chat"
version = "1.0.0"
description = "Chuột Chat Flask app"
authors = ["none <none@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
Flask = "2.3.2"
psycopg2-binary = "2.9.7"
requests = "2.31.0"